DROP DATABASE IF EXISTS "MSDS";
CREATE DATABASE "MSDS";

DROP TABLE IF EXISTS "MSDSCourseCatalog";
DROP TABLE IF EXISTS "MSDSCourseCatalog";

\c "MSDS";

CREATE TABLE "MSDSCourseCatalog" (
    "CID" VARCHAR(7) PRIMARY KEY,
    "CNAME" VARCHAR(50),
    "CPREREQ" VARCHAR(50)
);
