apiVersion: v1
kind: Pod
metadata:
  name: datalake-api
  labels:
    app: api
spec:
  containers:
  - name: datalake-api
    image: ericesn/datalake-api:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080  # The port your application connects to
      targetPort: 8080  # The port exposed by the PostgreSQL container
  type: NodePort  # Allows access to the Service on a port of the host machine
