apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: datapull
  name: datapull
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datapull
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: datapull
    spec:
      containers:
        - image: ericesn/datalake-datapull
          name: datapull
      restartPolicy: Always
