version: '3.8'

services:
  geocoder:
    build: ./geocoder
    ports:
      - "8080:8080"
    depends_on:
      - db

  datapull:
    build:
      context: ./datapull
    # ports:
    #   - "8081:8081"
    # depends_on:
    #   - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional SQL initialization file
    ports:
      - "5432:5432"

volumes:
  db-data:
