version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    # depends_on:
      # - postgres

  datapull:
    build:
      context: .
      dockerfile: ./datapull/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: msds432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      # Use something other than port 5432 for the host machine to avoid conflicts
      - "5431:5432"

volumes:
  postgres-data:
